---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-lvm
      lvm_volume_groups:
        - name: first
          pvs:
            - /dev/loop0

      # There is no device mapper in containers.
      # lvm_logical_volumes:
      #   - name: first
      #     vg: first
      #     size: 100%FREE
      #     opts: --type cache-pool
