---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.lvm
      # It's difficult to test this in CI.
      # lvm_volume_groups:
      #   - name: first
      #     pvs:
      #       - /dev/loop0

      # There is no device mapper in containers.
      # lvm_logical_volumes:
      #   - name: first
      #     vg: first
      #     size: 100%FREE
      #     opts: --type cache-pool
